### PR TITLE
Add documentation for Zulip notifications

### PR DESCRIPTION
**Pull request by punchagan**
Support for Zulip notifications was added in upptime/uptime-monitor#198

### CODE REVIEW

**Comment by AnandChowdhary** [comment]
Thank you!

**Comment by punchagan** [comment]
@AnandChowdhary any chance this could be released as a new version of uptime-monitor? Or is there a way to be able to use the git version of uptime-monitor in my actions?

**Comment by AnandChowdhary** [comment]
For sure! Released here: https://github.com/upptime/uptime-monitor/releases/tag/v1.29.0 and on npm!

**Comment by punchagan** [comment]
Thanks a ton! :tada:

**Pull request merged**
